/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question?: string;
  answer?: string;
  defaultOpen?: boolean;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors?: Array<{
    authorType?: "person" | "name";
    person?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "people";
    };
    name?: string;
    _key: string;
  }>;
  tags?: Array<string>;
  status?: "published" | "review" | "progress" | "draft";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
};

export type People = {
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = Faq | Project | SanityImageCrop | SanityImageHotspot | News | People | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/faq/getFAQs.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(orderRank)
export type FaqsQueryResult = Array<{
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question?: string;
  answer?: string;
  defaultOpen?: boolean;
}>;

// Source: ./src/sanity/lib/news/getNews.ts
// Variable: newsQuery
// Query: *[_type == "news"] | order(date desc)[0...3]
export type NewsQueryResult = Array<{
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
}>;

// Source: ./src/sanity/lib/people/getPeople.ts
// Variable: currentPeopleQuery
// Query: *[_type == "people" && status == "active"] | order(name asc)
export type CurrentPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;
// Variable: alumniPeopleQuery
// Query: *[_type == "people" && status == "alumni"] | order(end desc, name asc)
export type AlumniPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;
// Variable: collaboratorsPeopleQuery
// Query: *[_type == "people" && status == "collaborator"] | order(name asc)
export type CollaboratorsPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;

// Source: ./src/sanity/lib/projects/getProjects.ts
// Variable: projectQuery
// Query: *[_type == "project"] | order(date desc)[0...2] {      ...,      authors[] {        authorType,        authorType == "person" => {          "name": person->name        },        authorType == "name" => {          name        }      }    }
export type ProjectQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors: Array<{
    authorType: "name" | "person" | null;
    name: string | null;
  } | {
    authorType: "name" | "person" | null;
  }> | null;
  tags?: Array<string>;
  status?: "draft" | "progress" | "published" | "review";
}>;
// Variable: projectOrderedQuery
// Query: *[_type == "project"] | order(orderRank)[0...2] {      ...,      authors[] {        authorType,        authorType == "person" => {          "name": person->name        },        authorType == "name" => {          name        }      }    }
export type ProjectOrderedQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors: Array<{
    authorType: "name" | "person" | null;
    name: string | null;
  } | {
    authorType: "name" | "person" | null;
  }> | null;
  tags?: Array<string>;
  status?: "draft" | "progress" | "published" | "review";
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"faq\"] | order(orderRank)\n  ": FaqsQueryResult;
    "\n    *[_type == \"news\"] | order(date desc)[0...3]\n  ": NewsQueryResult;
    "\n    *[_type == \"people\" && status == \"active\"] | order(name asc)\n  ": CurrentPeopleQueryResult;
    "\n    *[_type == \"people\" && status == \"alumni\"] | order(end desc, name asc)\n  ": AlumniPeopleQueryResult;
    "\n    *[_type == \"people\" && status == \"collaborator\"] | order(name asc)\n  ": CollaboratorsPeopleQueryResult;
    "\n    *[_type == \"project\"] | order(date desc)[0...2] {\n      ...,\n      authors[] {\n        authorType,\n        authorType == \"person\" => {\n          \"name\": person->name\n        },\n        authorType == \"name\" => {\n          name\n        }\n      }\n    }\n  ": ProjectQueryResult;
    "\n    *[_type == \"project\"] | order(orderRank)[0...2] {\n      ...,\n      authors[] {\n        authorType,\n        authorType == \"person\" => {\n          \"name\": person->name\n        },\n        authorType == \"name\" => {\n          name\n        }\n      }\n    }\n  ": ProjectOrderedQueryResult;
  }
}
