/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Conference = {
  _id: string;
  _type: "conference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  location?: string;
  coordinates?: {
    lat?: number;
    lng?: number;
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  dates?: string;
  abbreviation?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ImageSettings = {
  _id: string;
  _type: "imageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  sectionKey?: "home-hero" | "home-why-hci" | "home-featured-projects" | "home-hub-community" | "about-hero" | "about-studio-time" | "about-lab-values" | "events-owl-hacks" | "events-open-house" | "events-social" | "events-conference" | "contact-serc" | "research-hero" | "people-hero" | "courses-hero" | "sponsors-hero" | "join-hero";
  singleImage?: {
    asset?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
  };
  imageArray?: Array<{
    asset?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    _key: string;
  }>;
};

export type Testimonials = {
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  quote?: string;
  person?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "people";
  };
  role?: string;
  isActive?: boolean;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question?: string;
  answer?: string;
  defaultOpen?: boolean;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors?: Array<{
    authorType?: "person" | "name";
    person?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "people";
    };
    name?: string;
    _key: string;
  }>;
  tags?: Array<string>;
  status?: "published" | "review" | "progress" | "draft";
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  category?: "Gen AI & Education" | "Accessibility Technology" | "Social Computing";
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  actions?: Array<{
    label?: "pdf" | "demo" | "code" | "cite" | "talk";
    url?: string;
    _key: string;
  }>;
  featured?: boolean;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "Collaborations" | "Grants / Awards" | "Conference Talk" | "Published Papers" | "Alumni";
  featured?: boolean;
};

export type People = {
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = Conference | SanityImageCrop | SanityImageHotspot | ImageSettings | Testimonials | Faq | Project | Research | News | People | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/conference/getConference.ts
// Variable: conferencesQuery
// Query: *[_type == "conference"]
export type ConferencesQueryResult = Array<{
  _id: string;
  _type: "conference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  location?: string;
  coordinates?: {
    lat?: number;
    lng?: number;
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  dates?: string;
  abbreviation?: string;
}>;

// Source: ./src/sanity/lib/faq/getFAQs.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(orderRank)
export type FaqsQueryResult = Array<{
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question?: string;
  answer?: string;
  defaultOpen?: boolean;
}>;

// Source: ./src/sanity/lib/imageSettings/aboutImages.ts
// Variable: aboutHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "about-hero"][0].singleImage
export type AboutHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;
// Variable: aboutStudioTimeQuery
// Query: *[_type == "imageSettings" && sectionKey == "about-studio-time"][0].singleImage
export type AboutStudioTimeQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;
// Variable: aboutLabValuesQuery
// Query: *[_type == "imageSettings" && sectionKey == "about-lab-values"][0].imageArray
export type AboutLabValuesQueryResult = Array<{
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  _key: string;
}> | null;
// Variable: aboutEventOwlHacksQuery
// Query: *[_type == "imageSettings" && sectionKey == "events-owl-hacks"][0].imageArray
export type AboutEventOwlHacksQueryResult = Array<{
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  _key: string;
}> | null;
// Variable: aboutEventOpenHouseQuery
// Query: *[_type == "imageSettings" && sectionKey == "events-open-house"][0].imageArray
export type AboutEventOpenHouseQueryResult = Array<{
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  _key: string;
}> | null;
// Variable: aboutEventSocialQuery
// Query: *[_type == "imageSettings" && sectionKey == "events-social"][0].imageArray
export type AboutEventSocialQueryResult = Array<{
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  _key: string;
}> | null;
// Variable: aboutConferenceTravelQuery
// Query: *[_type == "imageSettings" && sectionKey == "events-conference"][0].singleImage
export type AboutConferenceTravelQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;
// Variable: aboutSercQuery
// Query: *[_type == "imageSettings" && sectionKey == "contact-serc"][0].singleImage
export type AboutSercQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/coursesImages.ts
// Variable: coursesHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "courses-hero"][0].singleImage
export type CoursesHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/homeImages.ts
// Variable: homeHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "home-hero"][0].singleImage
export type HomeHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;
// Variable: homeWhyHCIQuery
// Query: *[_type == "imageSettings" && sectionKey == "home-why-hci"][0].imageArray
export type HomeWhyHCIQueryResult = Array<{
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  _key: string;
}> | null;
// Variable: homeFeaturedProjectsQuery
// Query: *[_type == "imageSettings" && sectionKey == "home-featured-projects"][0].singleImage
export type HomeFeaturedProjectsQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;
// Variable: homeHubCommunityQuery
// Query: *[_type == "imageSettings" && sectionKey == "home-hub-community"][0].singleImage
export type HomeHubCommunityQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/joinImages.ts
// Variable: joinHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "join-hero"][0].singleImage
export type JoinHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/peopleImages.ts
// Variable: peopleHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "people-hero"][0].singleImage
export type PeopleHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/researchImages.ts
// Variable: researchHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "research-hero"][0].singleImage
export type ResearchHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/imageSettings/sponsorsImages.ts
// Variable: sponsorsHeroQuery
// Query: *[_type == "imageSettings" && sectionKey == "sponsors-hero"][0].singleImage
export type SponsorsHeroQueryResult = {
  asset?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
} | null;

// Source: ./src/sanity/lib/news/getNews.ts
// Variable: recentNewsQuery
// Query: *[_type == "news"] | order(date desc)[0...3]
export type RecentNewsQueryResult = Array<{
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "Alumni" | "Collaborations" | "Conference Talk" | "Grants / Awards" | "Published Papers";
  featured?: boolean;
}>;
// Variable: allNewsQuery
// Query: *[_type == "news"] | order(date desc)
export type AllNewsQueryResult = Array<{
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "Alumni" | "Collaborations" | "Conference Talk" | "Grants / Awards" | "Published Papers";
  featured?: boolean;
}>;

// Source: ./src/sanity/lib/people/getPeople.ts
// Variable: currentPeopleQuery
// Query: *[_type == "people" && status == "active"] | order(orderRank)
export type CurrentPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;
// Variable: alumniPeopleQuery
// Query: *[_type == "people" && status == "alumni"] | order(orderRank)
export type AlumniPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;
// Variable: collaboratorsPeopleQuery
// Query: *[_type == "people" && status == "collaborator"] | order(orderRank)
export type CollaboratorsPeopleQueryResult = Array<{
  _id: string;
  _type: "people";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name?: string;
  url?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  roles?: Array<string>;
  status?: "active" | "alumni" | "collaborator";
  start?: number;
  end?: number;
  affiliation?: string;
  now?: string;
}>;

// Source: ./src/sanity/lib/projects/getProjects.ts
// Variable: projectQuery
// Query: *[_type == "project"] | order(date desc)[0...2] {      ...,      authors[] {        authorType,        authorType == "person" => {          "name": person->name        },        authorType == "name" => {          name        }      }    }
export type ProjectQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors: Array<{
    authorType: "name" | "person" | null;
    name: string | null;
  } | {
    authorType: "name" | "person" | null;
  }> | null;
  tags?: Array<string>;
  status?: "draft" | "progress" | "published" | "review";
}>;
// Variable: projectOrderedQuery
// Query: *[_type == "project"] | order(orderRank)[0...2] {      ...,      authors[] {        authorType,        authorType == "person" => {          "name": person->name        },        authorType == "name" => {          name        }      }    }
export type ProjectOrderedQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  date?: string;
  link?: string;
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  authors: Array<{
    authorType: "name" | "person" | null;
    name: string | null;
  } | {
    authorType: "name" | "person" | null;
  }> | null;
  tags?: Array<string>;
  status?: "draft" | "progress" | "published" | "review";
}>;

// Source: ./src/sanity/lib/research/getResearch.ts
// Variable: genAIEducationQuery
// Query: *[_type == "research" && category == "Gen AI & Education"] | order(orderRank)
export type GenAIEducationQueryResult = Array<{
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  category?: "Accessibility Technology" | "Gen AI & Education" | "Social Computing";
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  actions?: Array<{
    label?: "cite" | "code" | "demo" | "pdf" | "talk";
    url?: string;
    _key: string;
  }>;
  featured?: boolean;
}>;
// Variable: accessibilityTechQuery
// Query: *[_type == "research" && category == "Accessibility Technology"] | order(orderRank)
export type AccessibilityTechQueryResult = Array<{
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  category?: "Accessibility Technology" | "Gen AI & Education" | "Social Computing";
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  actions?: Array<{
    label?: "cite" | "code" | "demo" | "pdf" | "talk";
    url?: string;
    _key: string;
  }>;
  featured?: boolean;
}>;
// Variable: socialComputingQuery
// Query: *[_type == "research" && category == "Social Computing"] | order(orderRank)
export type SocialComputingQueryResult = Array<{
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  description?: string;
  category?: "Accessibility Technology" | "Gen AI & Education" | "Social Computing";
  imageUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  actions?: Array<{
    label?: "cite" | "code" | "demo" | "pdf" | "talk";
    url?: string;
    _key: string;
  }>;
  featured?: boolean;
}>;

// Source: ./src/sanity/lib/testimonials/getTestimonials.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonials" && isActive == true] | order(orderRank) {      _id,      quote,      role,      person-> {        name,        img      }    }
export type TestimonialsQueryResult = Array<{
  _id: string;
  quote: string | null;
  role: string | null;
  person: {
    name: string | null;
    img: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"conference\"]\n  ": ConferencesQueryResult;
    "\n    *[_type == \"faq\"] | order(orderRank)\n  ": FaqsQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"about-hero\"][0].singleImage\n  ": AboutHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"about-studio-time\"][0].singleImage\n  ": AboutStudioTimeQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"about-lab-values\"][0].imageArray\n  ": AboutLabValuesQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"events-owl-hacks\"][0].imageArray\n  ": AboutEventOwlHacksQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"events-open-house\"][0].imageArray\n  ": AboutEventOpenHouseQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"events-social\"][0].imageArray\n  ": AboutEventSocialQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"events-conference\"][0].singleImage\n  ": AboutConferenceTravelQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"contact-serc\"][0].singleImage\n  ": AboutSercQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"courses-hero\"][0].singleImage\n  ": CoursesHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"home-hero\"][0].singleImage\n  ": HomeHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"home-why-hci\"][0].imageArray\n  ": HomeWhyHCIQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"home-featured-projects\"][0].singleImage\n  ": HomeFeaturedProjectsQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"home-hub-community\"][0].singleImage\n  ": HomeHubCommunityQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"join-hero\"][0].singleImage\n  ": JoinHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"people-hero\"][0].singleImage\n  ": PeopleHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"research-hero\"][0].singleImage\n  ": ResearchHeroQueryResult;
    "\n    *[_type == \"imageSettings\" && sectionKey == \"sponsors-hero\"][0].singleImage\n  ": SponsorsHeroQueryResult;
    "\n    *[_type == \"news\"] | order(date desc)[0...3]\n  ": RecentNewsQueryResult;
    "\n    *[_type == \"news\"] | order(date desc)\n  ": AllNewsQueryResult;
    "\n    *[_type == \"people\" && status == \"active\"] | order(orderRank)\n  ": CurrentPeopleQueryResult;
    "\n    *[_type == \"people\" && status == \"alumni\"] | order(orderRank)\n  ": AlumniPeopleQueryResult;
    "\n    *[_type == \"people\" && status == \"collaborator\"] | order(orderRank)\n  ": CollaboratorsPeopleQueryResult;
    "\n    *[_type == \"project\"] | order(date desc)[0...2] {\n      ...,\n      authors[] {\n        authorType,\n        authorType == \"person\" => {\n          \"name\": person->name\n        },\n        authorType == \"name\" => {\n          name\n        }\n      }\n    }\n  ": ProjectQueryResult;
    "\n    *[_type == \"project\"] | order(orderRank)[0...2] {\n      ...,\n      authors[] {\n        authorType,\n        authorType == \"person\" => {\n          \"name\": person->name\n        },\n        authorType == \"name\" => {\n          name\n        }\n      }\n    }\n  ": ProjectOrderedQueryResult;
    "\n    *[_type == \"research\" && category == \"Gen AI & Education\"] | order(orderRank)\n  ": GenAIEducationQueryResult;
    "\n    *[_type == \"research\" && category == \"Accessibility Technology\"] | order(orderRank)\n  ": AccessibilityTechQueryResult;
    "\n    *[_type == \"research\" && category == \"Social Computing\"] | order(orderRank)\n  ": SocialComputingQueryResult;
    "\n    *[_type == \"testimonials\" && isActive == true] | order(orderRank) {\n      _id,\n      quote,\n      role,\n      person-> {\n        name,\n        img\n      }\n    }\n  ": TestimonialsQueryResult;
  }
}
