export const QUOTES = [
  { quote: "That's a Steve question.", name: "Literally Everyone", size: 22, opacity: 1.0 },
  { quote: "Where is your database?!", name: "Silas C", size: 20, opacity: 0.95 },
  { quote: "Smells like deceit!", name: "Kate O", size: 19, opacity: 1.0 },
  { quote: "…Battery Acid", name: "Kenny", size: 20, opacity: 0.95 },
  { quote: "Poetry", name: "Ashfin", size: 21, opacity: 0.9 },
  { quote: "I have acid!", name: "Kenny", size: 19, opacity: 0.9 },
  { quote: "It needs more salt", name: "Kate O", size: 18, opacity: 0.85 },
  { quote: "The council is deciding your fate… Lobotomy", name: "Kate O", size: 15, opacity: 0.88 },
  { quote: "Wait I'm goated, stay humble", name: "Emily Goat × Kate H", size: 16, opacity: 0.88 },
  { quote: "There were beans in the fountain?", name: "Emily", size: 16, opacity: 0.82 },
  { quote: "The day you meet Steve.", name: "Kush Patel", size: 15, opacity: 0.78 },
  { quote: "I miss the uncs :(", name: "Daniel B.", size: 15, opacity: 0.78 },
  { quote: "You look like young Zuc", name: "Mann", size: 15, opacity: 0.78 },
  { quote: "The potato is quality", name: "Kush", size: 15, opacity: 0.72 },
  { quote: "Thank you! Thank you! Thank you!", name: "Kush, Ashfin, Antonio", size: 14, opacity: 0.7 },
  { quote: "I'll whoop you in Jeans", name: "Thanh", size: 14, opacity: 0.68 },
  { quote: "Do you want to hang out… like socially?", name: "Nadia", size: 13, opacity: 0.68 },
  { quote: "I like your fan. I like you.", name: "Jess", size: 13, opacity: 0.62 },
  { quote: "Looks like a Cinnamon roll. Could kill you.", name: "Jess", size: 12, opacity: 0.62 },
  { quote: "Antonio's kind of like Obama in that way", name: "Emily M", size: 12, opacity: 0.62 },
  { quote: "Why is Egi kinda Kenny nowadays", name: "Danny", size: 12, opacity: 0.58 },
  { quote: "I can joke like that but you can't.", name: "Kate H", size: 12, opacity: 0.58 },
  { quote: "GOATS everywhere for those with eyes to see", name: "Emily Goat", size: 12, opacity: 0.62 },
  { quote: "Pigeons are sky rats, seagulls are beach rats,\nsquirrels are forest rats, bats are night rats.", name: "Kate O", size: 11, opacity: 0.65 },
  { quote: "Do you have any Traceable cultural background?", name: "Emily", size: 11, opacity: 0.52 },
  { quote: "If it's not in English, what language is it?", name: "Kate H", size: 11, opacity: 0.52 },
];

export const QUOTE_COLORS = ["#AA2C45", "#AA2C45", "#8B1E35", "#2d2d2d", "#AA2C45", "#6b1428"];
